ISP_FTP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ISP_FTP import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls'), name='movies'),
    path('tv/', include('tv_series.urls'), name='tv'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'movie'

urlpatterns = [
    path('', views.MovieList.as_view(), name='list'),
    path('<int:pk>/', views.MovieDetails.as_view(), name='details'),
    path('create/', views.MovieCreate.as_view(), name='create'),
    path('create-file/', views.addMovieWithFile.as_view(), name='create-file'),
    path('auto-create/', views.MovieAutoCreate.as_view(), name='auto-create')
]

tv_series/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'tv'

urlpatterns = [
    path('', views.TVList.as_view(), name='list'),
    path('<int:pk>/', views.TVDetails.as_view(), name='details'),
    path('create/', views.TVCreate.as_view(), name='create'),
    path('create-file/', views.AddTVWithFile.as_view(), name='create-file'),
    path('auto-create/', views.TVAutoCreate.as_view(), name='auto-create'),


    path('episodes/<path:ddir>', views.episodes, name='get-eps'),


]

movies/models.py
from django.db import models


class Movies(models.Model):
    name = models.CharField(max_length=300)
    year = models.IntegerField(blank=True, null=True)
    genre = models.CharField(max_length=10, blank=True, null=True)
    photo = models.ImageField(upload_to='movie_photos', max_length=1000, blank=True, null=True)
    cast = models.CharField(max_length=9999)
    plot = models.CharField(max_length=9999)
    synopsis = models.CharField(max_length=999999)
    video = models.CharField(max_length=1000, help_text="Put the link to your movie file", blank=True, null=True)
    imdb_found = models.BooleanField(default=False, blank=True, null=True)
    manual = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    rating = models.CharField(max_length=4, null=True)
    imdbid = models.CharField(max_length=20, null=True)

    def __str__(self):
        return '{name}'.format(name=self.name)

tv_series/models.py
from django.db import models

# Create your models here.
class TV(models.Model):
    name = models.CharField(max_length=300)
    year = models.IntegerField(blank=True, null=True)
    genre = models.CharField(max_length=10, blank=True, null=True)
    photo = models.ImageField(upload_to='movie_photos', max_length=1000, blank=True, null=True)
    cast = models.CharField(max_length=9999)
    plot = models.CharField(max_length=9999)
    synopsis = models.CharField(max_length=999999)
    dir = models.CharField(max_length=1000, help_text="Put the link to your TV series directory", blank=True, null=True)
    imdb_found = models.BooleanField(default=False, blank=True, null=True)
    manual = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    rating = models.CharField(max_length=4, null=True)
    imdbid = models.CharField(max_length=20, null=True)


    def __str__(self):
        return '{name}'.format(name=self.name)

movies/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView


from movies.modelforms import CreateMoviesForm, CreateFromVideo
from movies.models import Movies

from etc_files import get_movie, get_movie_file


class MovieList(ListView):
    model = Movies
    template_name = 'movie_list.html'
    queryset = Movies.objects.all()
    context_object_name = 'movies'


class MovieDetails(DetailView):
    model = Movies
    template_name = 'movie_detail.html'
    queryset = Movies.objects.all()
    context_object_name = 'movie'


class MovieCreate(CreateView):
    template_name = 'movie_create.html'
    model = Movies
    form_class = CreateMoviesForm
    queryset = Movies.objects.all()
    success_url = reverse_lazy('movie:list')




class MovieAutoCreate(CreateView):
    template_name = "movie_auto.html"
    # form_class = Auto

    def get(self, request, *args, **kwargs):
        return render(request, template_name=self.template_name)

    def post(self, request, *args, **kwargs):
        print("CRAWLING")
        data = request.POST
        d = {}
        for key, value in data.items():
            d[key] = value

        del d['csrfmiddlewaretoken']

        directory = d["directory"]
        get_movie(directory)
        return redirect(reverse_lazy('movie:list'))


class addMovieWithFile(CreateView):
    template_name = "movie_create_file.html"
    # form_class = CreateFromVideo
    f = CreateFromVideo()

    def get(self, request, *args, **kwargs):
        return render(request, template_name=self.template_name, context={'form': self.f})

    def post(self, request, *args, **kwargs):
        data = request.POST
        d = {}
        for key, value in data.items():
            d[key] = value

        del d['csrfmiddlewaretoken']

        video = d['video']
        name = d['name']
        get_movie_file(video, name)
        return redirect(reverse_lazy('movie:list'))

tv_series/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, CreateView

from etc_files import get_tv, get_tv_file, get_seasons, get_episodes
from tv_series.modelforms import CreateTvsForm, CreateFromVideo
from tv_series.models import TV


class TVList(ListView):
    model = TV
    template_name = 'tv_list.html'
    queryset = TV.objects.all()
    context_object_name = 'tvs'


class TVDetails(DetailView):
    model = TV
    template_name = 'tv_detail.html'
    queryset = TV.objects.all()
    context_object_name = 'tv'

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        tv_obj_detail = super().get_object()
        dir = tv_obj_detail.dir
        seasons = get_seasons(dir)
        data['seasons'] = seasons
        return data


class TVCreate(CreateView):
    template_name = 'tv_create.html'
    model = TV
    form_class = CreateTvsForm
    queryset = TV.objects.all()
    success_url = reverse_lazy('tv:list')


class TVAutoCreate(CreateView):
    template_name = "tv_auto.html"
    # form_class = Auto

    def get(self, request, *args, **kwargs):
        return render(request, template_name=self.template_name)

    def post(self, request, *args, **kwargs):
        print("CRAWLING")
        data = request.POST
        d = {}
        for key, value in data.items():
            d[key] = value

        del d['csrfmiddlewaretoken']

        directory = d["directory"]
        get_tv(directory)
        return redirect(reverse_lazy('tv:list'))


class AddTVWithFile(CreateView):
    template_name = "tv_create_file.html"
    # form_class = CreateFromVideo
    f = CreateFromVideo()

    def get(self, request, *args, **kwargs):
        return render(request, template_name=self.template_name, context={'form': self.f})

    def post(self, request, *args, **kwargs):
        data = request.POST
        d = {}
        for key, value in data.items():
            d[key] = value

        del d['csrfmiddlewaretoken']

        dir = d['dir']
        name = d['name']
        get_tv_file(dir, name)
        return redirect(reverse_lazy('tv:list'))


def episodes(request, ddir):
    template_name = 'tv_episodes.html'
    episodes = get_episodes(ddir)
    return render(request, template_name=template_name, context={'episodes': episodes})

movies/templates/movie_auto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Movies</title>
</head>
<body>


<form method="post" action=".">
    {% csrf_token %}
    <input type="text" name="directory">
    <input type="submit" value="Submit">
</form>

</body>
</html>

movies/templates/movie_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Movie</title>
</head>
<body>

    <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Save">
    </form>


</body>
</html>

movies/templates/movie_create_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form enctype="multipart/form-data" method="post" action=".">
        {% csrf_token %}
        {{ form }}
{#        <input type="text" name="name">#}
{#        <input type="text" name="video">#}

        <input type="submit" value="Save">
    </form>

</body>
</html>

movies/templates/movie_detail.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="../../static/bootstrap/dist/css/bootstrap.min.css">
<script src="../../static/bootstrap/dist/js/bootstrap.min.js"></script> 

<link rel="stylesheet" href="../../static/css/movie_detail.css">

<body class="container-fluid pt-3">
    
    <div class="d-flex">

        <!-- LEFT -->
        <div id="leftBar" class="d-flex flex-column align-items-center pt-5" style="width: 48vw;" >
            <h4>{{ movie.name }}</h4> 
            <h6>{{ movie.genre }}</h6>
            <h6>{{ movie.year }}</h6>
            <h6>{{ movie.rating }}</h6>
            <h6 class="pr-5 pl-5" >{{ movie.plot }}</h6>
            <img src="{{ MEDIA_URL }}{{ movie.photo }}" alt="{{ movie.name }}" style="width: 15vw;">
        </div>

        

        <!-- RIGHT -->
        <div id="rightBar" class=""  style="width: 50vw; padding-top: 22vh;">

            <video id='my-video' class='video-js' controls preload='auto' width='900vw' height='400vh'
            poster="/media/{{ movie.photo }}"  data-setup='{}'>
            <source src=' {{ movie.video }}' type='video/mp4'>
            <p class='vjs-no-js'>
                To view this video please enable JavaScript, and consider upgrading to a web browser that
                <a href='https://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a>
            </p>
            </video>
            
        </div>

    </div>


    <!-- BOTTOM -->
    <div id="bottomBar pt-5" style="margin-top: 5vh;">

        <div class="pr-5 pl-5">
            <h4>Synopsis :</h4>
            <h6 class="pr-5 pl-5">{{ movie.synopsis }}</h6>
        </div>
        


        <div class="pr-5 pl-5">
            <h4>Cast :</h4>
            <h6 class="pr-5 pl-5">{{ movie.cast }}</h6>
        </div>
    </div>
    
    


</body>
{% endblock %}

movies/templates/movie_list.html
{% extends 'base.html' %}
{% block content %}

 <link rel="stylesheet" href="../static/bootstrap/dist/css/bootstrap.min.css">
    <script src="../static/bootstrap/dist/js/bootstrap.min.js"></script> 



<link rel="stylesheet" href="../../static/css/movie_list.css">

<body class="container-fluid pt-3">
    <!-- row justify-content-center -->
    <div id="moviesContainer" class="d-flex flex-lg-wrap justify-content-center">
        {% for movie in movies %}
        <div class="movieCard">
            <a href="{% url 'movie:details' movie.pk %}">
                <div class="card img-fluid align-items-center text-info bg-dark" style="width: 20vw; height: 60vh;">
                    <img class="card-img-top pr-2 pl-2 pb-2 " src="{{ MEDIA_URL }}{{ movie.photo }}" alt="{{ movie.name }}" style="width:20vw; height: 40vh;">
                    <h4 class="card-title" style="text-align: center;">{{ movie.name }}</h4>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>





</body>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% load static %}
    
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="/../static/css/base.css">
    <!-- <link rel="stylesheet" href="../static/bootstrap/dist/css/bootstrap.min.css">
    <script src="../static/bootstrap/dist/js/bootstrap.min.js"></script> -->
    
</head>


<body>
    <div id="header" class="header">
        <!-- NAVIGATION BAR -->
        <nav id="navbar" class="navbar navbar-expand-sm justify-content-center py-4">
            <a class="navbar-brand mr-auto" href="#">ISP</a>
            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{% url 'movie:list'%}">Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{% url 'tv:list'%}">TV Series</a>
                </li>
            </ul>
        </nav>
    </div>
{% block content %}
{% endblock %}

    <div id="footer" class="footer"> <h4>UNDER DEVELOPMENT this is a sample footer</h4> </div>

</body>
</html>

tv_series/templates/tv_auto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Movies</title>
</head>
<body>


<form method="post" action=".">
    {% csrf_token %}
    <input type="text" name="directory">
    <input type="submit" value="Submit">
</form>

</body>
</html>

tv_series/templates/tv_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Movie</title>
</head>
<body>

    <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Save">
    </form>


</body>
</html>

tv_series/templates/tv_create_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form enctype="multipart/form-data" method="post" action=".">
        {% csrf_token %}
        {{ form }}
{#        <input type="text" name="name">#}
{#        <input type="text" name="video">#}

        <input type="submit" value="Save">
    </form>

</body>
</html>

tv_series/templates/tv_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


{{ tv.name }}
{{ tv.type }}
{{ tv.year }}
{{ tv.photo }}
{{ tv.dir }}

<br>
{% for season in seasons %}

    <a href={% url 'tv:get-eps' ddir=season.1 %}> {{ season.0 }}</a>
    <br>

{% endfor %}


</body>
</html>

tv_series/templates/tv_episodes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<br>

{% for episode in episodes %}

    <a href="{{ episode.1 }}">{{ episode.0 }}</a>
    <br>

{% endfor %}


</body>
</html>

tv_series/templates/tv_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% for tv in tvs %}

    {{ tv.name }}
    {{ tv.type }}
    {{ tv.year }}
    {{ tv.photo }}
    <a href="{% url 'tv:details' tv.pk %}">Details</a>
    <img src="{{ MEDIA_URL }}{{ tv.photo }}" height="50" width="50">


{% endfor %}

</body>
</html>